# Version: @v3
# This file configures the continuous integration and continuous delivery (CI/CD) pipeline
# for the REST API project developed in Java with Spring Boot.

name: CI/CD pipeline
# Define events triggering the pipeline
on:
  pull_request:
    branches:
      - main # Run pipeline on Pull Requests to main branch
  push:
    branches:
      - main # Run pipeline on push to main branch
jobs:
  build:
    runs-on: windows-latest # Use Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Action to clone the repository inside the container

    - name: Set up JDK 11
      uses: actions/setup-java@v3 # Set up JDK 11
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution

    - name: Create Maven Wrapper directories
      run: mkdir -p .mvn/wrapper

    - name: Download Maven Wrapper JAR
      run: curl -L -o .mvn/wrapper/maven-wrapper.jar https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.5/maven-wrapper-0.5.5.jar

    - name: Download Maven Wrapper Properties
      run: curl -L -o .mvn/wrapper/maven-wrapper.properties https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.5/maven-wrapper-0.5.5.properties

    - name: Set executable permissions for mvnw
      run: chmod +x mvnw mvnw.cmd

    - name: Build with Maven
      run: cmd /c mvnw.cmd clean package # Execute mvnw.cmd using cmd.exe

    - name: Store JAR Artifact # Save artifact.jar
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: target/*.jar
