#Version: @v3
# This file configures the continuous integration and continuous delivery (CI/CD) pipeline
# for the REST API project developed in Java with Spring Boot.

name: CI/CD pipeline
# Define events triggering the pipeline
on:
  pull_request:
    branches:
      - main # Run pipeline on Pull Requests to main branch
  push:
    branches:
      - main # Run pipeline on push to main branch
jobs:
  build:
    runs-on: windows-latest # Use Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Action to clone the repository inside the container

    - name: Set up JDK 11
      uses: actions/setup-java@v3 # Set up JDK 11
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution

    - name: Make mvnw executable
      run: chmod +x mvnw # add permisions

    - name: Build with Maven
      run: ./mvnw clean package # Execute mvnw

    - name: Store JAR Artifact # Save artifact.jar
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: target/*.jar