# Version: @v3
# This file configures the continuous integration and continuous delivery (CI/CD) pipeline
# for the REST API project developed in Java with Spring Boot.

name: CI/CD pipeline
# Define events triggering the pipeline
on:
  pull_request:
    branches:
      - main # Run pipeline on Pull Requests to main branch
  push:
    branches:
      - main # Run pipeline on push to main branch
jobs:
  build:
    runs-on: windows-latest # Use Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Action to clone the repository inside the container

    - name: Set up JDK 11
      uses: actions/setup-java@v3 # Set up JDK 11
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution

    - name: Create .mvn/wrapper directory
      run: mkdir -p .mvn/wrapper

    - name: Install Maven Wrapper
      run: |
        curl -L -o mvnw.cmd https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.5/maven-wrapper-0.5.5.jar
        curl -L -o .mvn/wrapper/maven-wrapper.jar https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.5/maven-wrapper-0.5.5.jar
        chmod +x mvnw.cmd
        
    - name: Build with Maven Wrapper
      run: cmd /c mvnw.cmd clean package # Execute Maven Wrapper using cmd.exe on Windows

    - name: Store JAR Artifact # Save artifact.jar
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: target/*.jar
