#Version: @v2
# This file configures the continuous integration and continuous delivery (CI/CD) pipeline
# for the REST API project developed in Java with Spring Boot.

name: CI/CD pipeline
# Define events triggering the pipeline
on:
  pull_request:
    branches:
      - main # Run pipeline on Pull Requests to main branch
  push:
    branches:
      - main # Run pipeline on push to main branch
jobs:
  build:
    runs-on: ubuntu-latest # Use Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Action to clone the repository inside the container

    - name: Set up JDK 11
      uses: actions/setup-java@v2 # Set up JDK 11
      with:
        java-version: '11'

    - name: add permisions to mvnw
      run: chmod +x mvnw  # Ensure mvnw is executable
        
    - name: Build with Maven 
      run: ./mvnw verify # Action to compile application

    - name: Store JAR Artifact # Save artifact.jar
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: target/*.jar